server:
  port: 8091    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 2
    leaseExpirationDurationInSeconds: 4
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: false
    lease:
      duration: 5

spring:
  application:
    name: phone-service    #service name

logging:
  level:
    com.example.howtodoinjava: DEBUG