server:
  port: 8092    #port number

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: order-service    #service name

logging:
  level:
    com.example.howtodoinjava: DEBUG